//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/11/2014 08:18:41 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace fPeerLending.Entities
{
    /// <summary>
    /// Represents a row of Contact data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class Contact
    {
        /// <summary>
        /// Gets or sets a int value for the ContactId column.
        /// </summary>
        [DataMember] 
        public int ContactId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Surname column.
        /// </summary>
        [DataMember]
        public string Surname { get; set; }

        /// <summary>
        /// Gets or sets a string value for the OtherNames column.
        /// </summary>
        [DataMember]
        public string OtherNames { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the DateOfBirth column.
        /// </summary>
        [DataMember]
        public DateTime DateOfBirth { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Gender column.
        /// </summary>
        [DataMember]
        public string Gender { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Telephone column.
        /// </summary>
        [DataMember]
        public string Telephone { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Email column.
        /// </summary>
        [DataMember]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the DateJoined column.
        /// </summary>
        [DataMember]
        public DateTime DateJoined { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Status column.
        /// </summary>
        [DataMember]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the DateActivated column.
        /// </summary>
        [DataMember]
        public DateTime DateActivated { get; set; }

        /// <summary>
        /// Gets or sets a int value for the RefferedBy column.
        /// </summary>
        [DataMember]
        public int RefferedBy { get; set; }

        /// <summary>
        /// Gets or sets a string value for the InformBy column.
        /// </summary>
        [DataMember]
        public string InformBy { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Photo column.
        /// </summary>
        [DataMember]
        public string Photo { get; set; }

        /// <summary>
        /// Gets or sets a string value for the NationalID column.
        /// </summary>
        [DataMember]
        public string NationalID { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Pwd column.
        /// </summary>
        [DataMember]
        public string Pwd { get; set; }
    }
}
