//====================================================================================================
// Code generated with Inertia: BE Gen (Build 2.5.4750.27569)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by fmuraya at SOFTBOOKSSERVER on 10/09/2013 13:53:43 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace fPeerLending.Entities
{
    /// <summary>
    /// Represents a row of ContactUs data.
    /// </summary>
    [DataContract]
    public partial class ContactUs
    {

        /// <summary>
        /// Gets or sets a int value for the Id column.
        /// </summary>
        [DataMember]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets a string value for the FirstName column.
        /// </summary>
        [DataMember]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or sets a string value for the LastName column.
        /// </summary>
        [DataMember]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Telephone column.
        /// </summary>
        [DataMember]
        public string Telephone { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Email column.
        /// </summary>
        [DataMember]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Subject column.
        /// </summary>
        [DataMember]
        public string Subject { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Comment column.
        /// </summary>
        [DataMember]
        public string Comment { get; set; }
    }
}
