//====================================================================================================
// Code generated with Inertia: BE Gen (Build 2.5.4750.27569)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by fmuraya at SOFTBOOKSSERVER on 08/31/2013 15:32:04 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;


namespace fPeerLending.Entities
{
    public class InstallmentsModel
    {
        #region "Installments"
        public DateTime expected_date
        {
            get;
            set;
        }
        public decimal interest_repayment
        {
            get;
            set;
        }
        public decimal capital_repayment
        {
            get;
            set;
        }
        public int contract_id
        {
            get;
            set;
        }
        public int number
        {
            get;
            set;
        }
        public decimal paid_interest
        {
            get;
            set;
        }
        public decimal paid_capital
        {
            get;
            set;
        }
        public decimal fees_unpaid
        {
            get;
            set;
        }
        public decimal paid_fees
        {
            get;
            set;
        }
        public string comment
        {
            get;
            set;
        }
        public bool pending
        {
            get;
            set;
        }
        public DateTime start_date
        {
            get;
            set;
        }
        public decimal olb
        {
            get;
            set;
        }
        public int installmentid
        {
            get;
            set;
        }
        public double installment_monthly_total
        {
            get;
            set;
        }
        public double principle
        {
            get;
            set;
        }
        public double interest
        {
            get;
            set;
        }
        public int months
        {
            get;
            set;
        }
        #endregion "Installments"
    }
}
