//====================================================================================================
// Code generated with Inertia: BE Gen (Build 2.5.4750.27569)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by fmuraya at SOFTBOOKSSERVER on 08/31/2013 15:32:04 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;


namespace fPeerLending.Entities
{
    public class InstallmentTypesModel
    {
        #region "InstallmentType"
        public int installmenttypesid
        {
            get;
            set;
        }
        public string name
        {
            get;
            set;
        }
        public int nb_of_days
        {
            get;
            set;
        }
        public int nb_of_months
        {
            get;
            set;
        }
        #endregion "InstallmentType"
    }
}
