//====================================================================================================
// Code generated with Inertia: BE Gen (Build 2.5.4750.27569)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by fmuraya at SOFTBOOKSSERVER on 08/16/2013 12:42:35 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;
using System.Linq;
using System.Runtime.Serialization;

namespace fPeerLending.Entities
{
    /// <summary>
    /// Represents a row of Loan data.
    /// </summary>
    [DataContract]
    public partial class Loan
    {

        /// <summary>
        /// Gets or sets a int value for the Id column.
        /// </summary>
        [DataMember] 
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the MemberId column.
        /// </summary>
        [DataMember]
        [Display(Name = "Member Id")]
        public int MemberId { get; set; }

        [DataMember]
        public Member _Member { get; set; }

        [DataMember]
        public Offer _Offer { get; set; }

        /// <summary>
        /// Gets or sets a int value for the OfferId column.
        /// </summary>
        [DataMember]
        [Display(Name = "Offer Id")]
        public int OfferId { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Amount column.
        /// </summary>
        [DataMember]
        [Display(Name = "Amount")]
        public decimal Amount { get; set; }

        /// <summary>
        /// Gets or sets a double value for the Interest column.
        /// </summary>
        [DataMember]
        [Display(Name = "Interest")]
        public double Interest { get; set; }

        /// <summary>
        /// Gets or sets a int value for the Term column.
        /// </summary>
        [DataMember]
        [Display(Name = "Term (in months)")]
        public int Term { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the CreatedDate column.
        /// </summary>
        [DataMember]
        [Display(Name = "Created Date")]
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the MaturityDate column.
        /// </summary>
        [DataMember]
        [Display(Name = "Maturity Date")]
        public DateTime MaturityDate { get; set; }
         

        /// <summary>
        /// Gets or sets a string value for the Interval column.
        /// </summary>
        [DataMember]
        [Display(Name = "Interval")]
        public string Interval { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the StartDate column.
        /// </summary>
        [DataMember]
        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the EndDate column.
        /// </summary>
        [DataMember]
        [Display(Name = "End Date")]
        public DateTime EndDate { get; set; }

        /// <summary>
        /// Gets or sets a int value for the STOType column.
        /// </summary>
        [DataMember]
        [Display(Name = "STO Type")]
        public int STOType { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the PartialPay column.
        /// </summary>
        [DataMember]
        [Display(Name = "Partial Pay")]
        public bool PartialPay { get; set; }

        /// <summary>
        /// Gets or sets a int value for the DrAccount column.
        /// </summary>
        [DataMember]
        [Display(Name = "Debit Account")]
        public int DrAccount { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CrAccount column.
        /// </summary>
        [DataMember]
        [Display(Name = "Credit Account")]
        public int CrAccount { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the PayAmount column.
        /// </summary>
        [DataMember]
        [Display(Name = "Pay Amount")]
        public decimal PayAmount { get; set; } 

        /// <summary>
        /// Gets or sets a short value for the LimitFlag column.
        /// </summary>
        [DataMember]
        [Display(Name = "Limit Flag")]
        public int LimitFlag { get; set; }

        /// <summary>
        /// Gets or sets a int value for the DrTxnType column.
        /// </summary>
        [DataMember]
        [Display(Name = "Debit TxnType")]
        public int DrTxnType { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CrTxnType column.
        /// </summary>
        [DataMember]
        [Display(Name = "Credit TxnType")]
        public int CrTxnType { get; set; } 

        /// <summary>
        /// Gets or sets a DateTime value for the NextPayDate column.
        /// </summary>
        [DataMember]
        [Display(Name = "Next Pay Date")]
        public DateTime NextPayDate { get; set; }

        /// <summary>
        /// Gets or sets a short value for the NoOfPayments column.
        /// </summary>
        [DataMember]
        [Display(Name = "No Of Payments")]
        public int NoOfPayments { get; set; }

        [DataMember]
        [Display(Name = "Commission Account")]
        public int CommissionAccount { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the TotalToPay column.
        /// </summary>
        [DataMember]
        [Display(Name = "Total To Pay")]
        public decimal TotalToPay { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the AmountPaid column.
        /// </summary>
        [DataMember]
        [Display(Name = "Amount Paid")]
        public decimal AmountPaid { get; set; }

        /// <summary>
        /// Gets or sets a short value for the FeesFlag column.
        /// </summary>
        [DataMember]
        [Display(Name = "Fees Flag")]
        public string FeesFlag { get; set; }

        [DataMember]
        [Display(Name = "Debit Member")]
        public int DrMember { get; set; }

        [DataMember]
        [Display(Name = "Credit Member")]
        public int CrMember { get; set; }

        [DataMember]
        [Display(Name = "Charge Who")]
        public string ChargeWho { get; set; }

        [DataMember]
        [Display(Name = "Is Loan Paid Up")]
        public bool IsLoanPaidUp { get; set; }


    }
}
