//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by francis.muraya at KPC0201M on 11/20/2014 15:39:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace fPeerLending.Entities
{
    /// <summary>
    /// Represents a row of MailingGroupMember data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class MailingGroupMember
    {
        /// <summary>
        /// Gets or sets a int value for the Id column.
        /// </summary>
        [DataMember] 
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the GroupId column.
        /// </summary>
        [DataMember]
        public int GroupId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the IdType column.
        /// </summary>
        [DataMember]
        public string IdType { get; set; }

        /// <summary>
        /// Gets or sets a int value for the Member column.
        /// </summary>
        [DataMember]
        public int Member { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Email column.
        /// </summary>
        [DataMember]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Telno column.
        /// </summary>
        [DataMember]
        public string Telno { get; set; }

        /// <summary>
        /// Gets or sets a string value for the MailingGroup column.
        /// </summary>
        [DataMember]
        public string MailingGroup { get; set; }
    }
}
