//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by francis.muraya at KPC0201M on 11/17/2014 14:42:24 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace fPeerLending.Entities
{
    /// <summary>
    /// Represents a row of MemberSettingsGroup data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class MemberSettingsGroup
    {
        /// <summary>
        /// Gets or sets a int value for the Id column.
        /// </summary>
        [DataMember] 
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets a string value for the GroupName column.
        /// </summary>
        [DataMember]
        public string GroupName { get; set; }

        /// <summary>
        /// Gets or sets a int value for the Parent column.
        /// </summary>
        [DataMember]
        public int Parent { get; set; }
    }
}
