//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 10/31/2014 18:21:58 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;
using System.Linq;
using System.Runtime.Serialization;


namespace fPeerLending.Entities
{
    /// <summary>
    /// Represents a row of Member data.
    /// </summary>
    [DataContract]
    public partial class Member
    {
        /// <summary>
        /// Gets or sets a int value for the MemberId column.
        /// </summary>
        [DataMember]
        [Display(Name = "Member Id")]
        public int MemberId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Surname column.
        /// </summary>
        [DataMember]
        [Display(Name = "Surname")]
        public string Surname { get; set; }

        /// <summary>
        /// Gets or sets a string value for the OtherNames column.
        /// </summary>
        [DataMember]
        [Display(Name = "Other Names")]
        public string OtherNames { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the DateOfBirth column.
        /// </summary>
        [DataMember]
        [Display(Name = "Date Of Birth")]
        public DateTime DateOfBirth { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Gender column.
        /// </summary>
        [DataMember]
        [Display(Name = "Gender")]
        public string Gender { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Telephone column.
        /// </summary>
        [DataMember]
        [Display(Name = "Telephone")]
        public string Telephone { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Email column.
        /// </summary>
        [DataMember]
        [Display(Name = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the DateJoined column.
        /// </summary>
        [DataMember]
        [Display(Name = "Date Joined")]
        public DateTime DateJoined { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CustomerId column.
        /// </summary>
        [DataMember]
        [Display(Name = "Customer Id")]
        public int CustomerId { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CurrentAccountId column.
        /// </summary>
        [DataMember]
        [Display(Name = "Current Account Id")]
        public int CurrentAccountId { get; set; }

        /// <summary>
        /// Gets or sets a int value for the LoanAccountId column.
        /// </summary>
        [DataMember]
        [Display(Name = "Loan Account Id")]
        public int LoanAccountId { get; set; }

        /// <summary>
        /// Gets or sets a int value for the InvestmentAccountId column.
        /// </summary>
        [DataMember]
        [Display(Name = "Investment Account Id")]
        public int InvestmentAccountId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Status column.
        /// </summary>
        [DataMember]
        [Display(Name = "Status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the DateActivated column.
        /// </summary>
        [DataMember]
        [Display(Name = "Date Activated")]
        public DateTime DateActivated { get; set; }

        /// <summary>
        /// Gets or sets a int value for the RefferedBy column.
        /// </summary>
        [DataMember]
        [Display(Name = "Reffered By")]
        public int RefferedBy { get; set; }

        /// <summary>
        /// Gets or sets a string value for the InformBy column.
        /// </summary>
        [DataMember]
        [Display(Name = "Inform By")]
        public string InformBy { get; set; }

        /// <summary>
        /// Gets or sets a int value for the MaxRecordsToDisplay column.
        /// </summary>
        [DataMember]
        [Display(Name = "Max Records To Display")]
        public int MaxRecordsToDisplay { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Photo column.
        /// </summary>
        [DataMember]
        [Display(Name = "Photo")]
        public string Photo { get; set; }

        /// <summary>
        /// Gets or sets a string value for the NationalID column.
        /// </summary>
        [DataMember]
        [Display(Name = "National ID")]
        public string NationalID { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Pwd column.
        /// </summary>
        [DataMember]
        [Display(Name = "Password")]
        public string Pwd { get; set; }
    }
}
