//====================================================================================================
// Code generated with Inertia: BE Gen (Build 2.5.4750.27569)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by fmuraya at SOFTBOOKSSERVER on 08/29/2013 15:00:02 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;
using System.Linq;
using System.Runtime.Serialization;

namespace fPeerLending.Entities
{
    /// <summary>
    /// Represents a row of Offer data.
    /// </summary>
    [DataContract]
    public partial class Offer
    {

        /// <summary>
        /// Gets or sets a int value for the Id column.
        /// </summary>
        [DataMember]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets a string value for the OfferType column.
        /// </summary>

        [DataMember]
        [Display(Name = "Offer Type")]
        [Required(ErrorMessage = "Please Select Offer Type")]
        public string OfferType { get; set; }

        /// <summary>
        /// Gets or sets a int value for the MemberId column.
        /// </summary>
        [DataMember]
        public int MemberId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Description column.
        /// </summary>
        [DataMember]
        [Required(ErrorMessage = "Description cannot be null, e.g borrow offer 10,000 or lend offer 20,000 ")]
        [Display(Name = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Offerees column.
        /// </summary>
        [DataMember]
        [Display(Name = "Offerees (comma separated list of Email Addresses, telnos or groups of Email Addresses)")]
        public string Offerees { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the ExpiryDate column.
        /// </summary>
        [DataMember]
        [Display(Name = "Expiry Date")]
        public DateTime ExpiryDate { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the CreatedDate column.
        /// </summary>
        [DataMember]
        [Display(Name = "Created Date")]
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Amount column.
        /// </summary>
        [DataMember]
        [Range(0, 1000000, ErrorMessage = "Amount must be between 0 and 1,000,000")]
        [Display(Name = "Amount")]
        public decimal Amount { get; set; }

        /// <summary>
        /// Gets or sets a int value for the Term column.
        /// </summary>
        [DataMember]
        [Display(Name = "Term (in months)")]
        public int Term { get; set; }

        /// <summary>
        /// Gets or sets a double value for the Interest column.
        /// </summary>
        [DataMember]
        [Display(Name = "Interest")]
        public double Interest { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Status column.
        /// </summary>
        [DataMember]
        [Display(Name = "Status")]
        public string Status { get; set; }

        [DataMember]
        [Display(Name = "Public Offer")]
        [Required(ErrorMessage = "Please Select Offer Type")]
        public string PublicOffer { get; set; }

        [DataMember]
        [Display(Name = "Partial Pay")]
        public bool PartialPay { get; set; }



    }
}