//====================================================================================================
// Code generated with Motion: BC Gen (Build 2.2.4750.27570)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by fmuraya at SOFTBOOKSSERVER on 08/24/2013 17:32:28 
//====================================================================================================

using fPeerLending.Data;
using fPeerLending.Entities;
using fPeerLending.Framework; 
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Configuration;
using System.Linq;
using System.Runtime.Serialization;

using fanikiwaGL.Business;
using fanikiwaGL.Entities;
using fanikiwaGL.Framework;
using fCommon.Utility;
using fCommissions.Commission.Business;
using fMessagingSystem.Entities;
using fPeerLending.Framework.ExceptionTypes;


namespace fPeerLending.Business
{
    /// <summary>
    /// Registration business component.
    /// </summary>
    public partial class RegistrationComponent
    {
        /// <summary>
        /// GetMemberByID business method. 
        /// </summary>
        /// <param name="email">A email value.</param>
        /// <returns>Returns a Member object.</returns>
        public Member GetMemberByID(int id)
        {
            Member result = default(Member);

            // Data access component declarations.
            MemberDAC memberDAC = new MemberDAC();

            // Step 1 - Calling SelectByEmail on MemberDAC.
            result = memberDAC.SelectById(id);
            return result;

        }

        /// <summary>
        /// GetRegisteredMembers business method. 
        /// </summary>
        /// <param name="email"> </param>
        /// <returns>Returns Members object.</returns>
        public List<Member> GetRegisteredMembers()
        {
            List<Member> members = new List<Member>();

            // Data access component declarations.
            MemberDAC memberDAC = new MemberDAC();

            // Step 1 - Calling Select  on MemberDAC.
            members = memberDAC.Select();
            return members;

        }

        public void UpdateMember(Member member)
        {
            // Data access component declarations.
            MemberDAC memberDAC = new MemberDAC();

            // Step 1 - Calling UpdateById on MemberDAC.
            memberDAC.UpdateById(member);
        }
        public void UploadMemberImage(Member member)
        {
            // Data access component declarations.
            MemberDAC memberDAC = new MemberDAC();

            // Step 1 - Calling UpdateById on MemberDAC.
            memberDAC.UploadMemberImage(member);
        }
        /// <summary>
        /// GetMemnberByEmail business method. 
        /// </summary>
        /// <param name="email">A email value.</param>
        /// <returns>Returns a Member object.</returns>
        public Member GetMemberByEmail(string email)
        {
            Member result = default(Member);

            // Data access component declarations.
            MemberDAC memberDAC = new MemberDAC();

            // Step 1 - Calling SelectByEmail on MemberDAC.
            result = memberDAC.SelectByEmail(email);

            if (result == null) throw new ArgumentNullException("email", "Member with email [" + email + "] not registered in Fanikiwa");

            return result;
        }
        public Member SelectMemberByEmail(string email)
        {
            Member result = default(Member);

            // Data access component declarations.
            MemberDAC memberDAC = new MemberDAC();

            // Step 1 - Calling SelectByEmail on MemberDAC.
            result = memberDAC.SelectByEmail(email);             

            return result;
        }
        /// <summary>
        /// GetMemberByPhone business method. 
        /// </summary>
        /// <param name="email">A phone value.</param>
        /// <returns>Returns a Member object.</returns>
        public Member GetMemberByPhone(string phone)
        {
            Member result = default(Member);

            // Data access component declarations.
            MemberDAC memberDAC = new MemberDAC();

            // Step 1 - Calling SelectByEmail on MemberDAC.
            result = memberDAC.SelectByTelephone(phone);

            if (result == null) throw new ArgumentNullException("Member with phone [" + phone + "] not registered in Fanikiwa");

            return result;
        }
        public Member SelectMemberByPhone(string phone)
        {
            Member result = default(Member);

            // Data access component declarations.
            MemberDAC memberDAC = new MemberDAC();

            // Step 1 - Calling SelectByEmail on MemberDAC.
            result = memberDAC.SelectByTelephone(phone);
             
            return result;
        }

        #region Check Registration
        public bool IsPhoneRegistered(string Phone)
        {
            // Data access component declarations.
            MemberDAC memberDAC = new MemberDAC();

            return (memberDAC.IsPhoneRegistered(Phone));
        }

        public bool Authenticated(string telephone, string pwd)
        {
            MemberDAC memberDAC = new MemberDAC();

            return (memberDAC.CountByTelephonePwd(telephone, pwd)>0);
        }
        public bool Authorized(string telephone, string pwd)
        {
            bool authorized = false;
            MemberDAC memberDAC = new MemberDAC();
            Member m = memberDAC.SelectByTelephone(telephone);
            //check status
            if (m.Status.Equals("A")) authorized = true; //member is active, so authorized

            //check other things coming later

            return authorized;
        }
        public bool IsEmailRegistered(string Email) 
        {
            // Data access component declarations.
            MemberDAC memberDAC = new MemberDAC();

            return (memberDAC.IsEmailRegistered(Email));

        }
        public bool ISPhoneAndEmailRegistered(string Phone, string Email)
        {
            return IsPhoneRegistered(Phone) && IsEmailRegistered(Email);
        }
        public bool IsNationalIDRegistered(string NationalId)
        {
            // Data access component declarations.
            MemberDAC memberDAC = new MemberDAC();

            return (memberDAC.IsNationalIDRegistered(NationalId));
        }
        public bool IsRegistered(string email, string phone, string ID)
        {
            MemberDAC memberDAC = new MemberDAC();
            return memberDAC.IsRegistered( ID,  email,  phone);
        }
        #endregion

        #region Registration via SMS
        public Member RegisterViaPhone(Member member)
        {
            return this.Register(member);
        }

        #endregion

        #region Registration via web
        /// <summary>
        /// Register business method. 
        /// </summary>
        /// <param name="member">A member value.</param>
        /// <returns>Returns a Member object.</returns>
        public Member RegisterViaWeb(Member member)
        {
            return this.Register(member);
        }
        #endregion


        #region Registration Common
        public Member Register(Member member)
        {
            Member _Member = default(Member);

            // Data access component declarations.
            MemberDAC memberDAC = new MemberDAC();

            // Step 1 - Calling Create on MemberDAC. Create a member using details from screen
            _Member = memberDAC.Create(member);

            //Step 2. Create a customer using details from the returned member in step 1 above

            StaticTransactionsComponent glServiceClient = new StaticTransactionsComponent();
            
            Customer customer = new Customer();
            //at this point, fill the customer with the details from the UI
            customer.MemberId = _Member.MemberId;
            customer.Name = _Member.Surname;
            customer.Email = _Member.Email;
            customer.Telephone = _Member.Telephone;
            customer.CreatedDate = DateTime.Now.Date;
            
            Customer customerReturned = glServiceClient.CreateCustomer(customer);
            if (customerReturned == null) throw new ArgumentNullException("Customer","GL Service did not create a valid customer");


            //Step 3. Create 3 accounts. Currentaccount, loanaccount and invesmentaccount using the customerReturned            
            Account currentAccount = new Account();
            currentAccount.AccountName = customerReturned.Name + " Curr A/c";
            currentAccount.CustomerId = customerReturned.CustomerId;
            currentAccount.COAId = Config.GetInt("CURRENT_ACC_COA_ID");
            currentAccount.AccountTypeId = Config.GetInt("CURRENT_ACC_TYPE_ID");
            currentAccount.BookBalance = 0;
            currentAccount.ClearedBalance = 0;
            currentAccount.Limit = 0;
            currentAccount.InterestRate = 0;
            currentAccount.AccruedInt = 0;
            currentAccount.LimitFlag = (short)AccountLimitStatus.PostingOverDrawingProhibited;
            

            Account loanaccount = new Account();
            loanaccount.AccountName = customerReturned.Name + " Loan A/c";
            loanaccount.CustomerId = customerReturned.CustomerId;
            loanaccount.COAId = Config.GetInt("LOAN_ACC_COA_ID");
            loanaccount.AccountTypeId = Config.GetInt("LOAN_ACC_TYPE_ID");
            loanaccount.BookBalance = 0;
            loanaccount.ClearedBalance = 0;
            loanaccount.Limit = 0;
            loanaccount.InterestRate = 0;
            loanaccount.AccruedInt = 0;

            Account invesmentaccount = new Account();
            invesmentaccount.AccountName = customerReturned.Name + " Inv A/c";
            invesmentaccount.CustomerId = customerReturned.CustomerId;
            invesmentaccount.COAId = Config.GetInt("INVESTMENT_ACC_COA_ID");
            invesmentaccount.AccountTypeId = Config.GetInt("INVESTMENT_ACC_TYPE_ID");
            invesmentaccount.BookBalance = 0;
            invesmentaccount.ClearedBalance = 0;
            invesmentaccount.Limit = 0;
            invesmentaccount.InterestRate = 0;
            invesmentaccount.AccruedInt = 0;
            invesmentaccount.LimitFlag = (short)AccountLimitStatus.PostingOverDrawingProhibited;

            Account currentAccountReturned = glServiceClient.OpenAccount(currentAccount);
            Account loanAccountReturned = glServiceClient.OpenAccount(loanaccount);
            Account investmentAccountReturned = glServiceClient.OpenAccount(invesmentaccount);

            //Step 4. Update the member account created in step1 with the three accounts
            _Member.CurrentAccountId = currentAccountReturned.AccountID;
            _Member.LoanAccountId = loanAccountReturned.AccountID;
            _Member.InvestmentAccountId = investmentAccountReturned.AccountID;

            //Step 5. Update the member account created in step1 with the customer id
            _Member.CustomerId = customerReturned.CustomerId;

            memberDAC.UpdateById(_Member);

            //Step 6. Create ROOT Mailing Group for member
            MailingGroupsComponent mc = new MailingGroupsComponent();
            mc.CreateRootMailingGroup(_Member.MemberId);

            return _Member;
        }
        #endregion

        /// <summary>
        /// DeRegister business method. 
        /// </summary>
        /// <param name="memberId">A memberId value.</param>
        public void DeRegister(Member member)
        {
            /* must not have loans arrears  -  i.e. the loan account = 0
             * must not have investments – i.e. the investment account = 0
             * must not have money in the current account – i.e. the current account = 0
             * must not have open offers(both lend or borrow)
             */

            /* 1.	The AccountingSystem closes all accounts associated with the member
             * 2.	The OfferBook closes all offers associated with the member
             * 3.	The MemberBook marks the member record as closed
             * 4.	The MessagingSystem informs the user of successful deregistration
             * 5.	The system displays to the user a registration screen
             */


            StaticTransactionsComponent sPostingClient = new StaticTransactionsComponent();
             
            ListOffersComponent lc = new ListOffersComponent();
            OfferDAC offerDAC = new OfferDAC();
            MemberDAC mDAC = new MemberDAC();

            // 1. The AccountingSystem closes all accounts associated with the member  
            Account curracc = sPostingClient.GetAccount(member.CurrentAccountId);
            //check if current account balance is equal to zero
            if (curracc.BookBalance > 0)
                throw new DeregistrationException("Current account balance must be 0");
            sPostingClient.CloseAccount(curracc);

            Account invacc = sPostingClient.GetAccount(member.InvestmentAccountId);
            //check if investment account balance is equal to zero
            if (invacc.BookBalance > 0)
                throw new DeregistrationException("Investment account balance must be 0");
            sPostingClient.CloseAccount(invacc);

            Account lnacc = sPostingClient.GetAccount(member.LoanAccountId);
            //check if loan account balance is equal to zero
            if (lnacc.BookBalance > 0)
                throw new DeregistrationException("Loan account balance must be 0");
            sPostingClient.CloseAccount(lnacc);

            // 2. The OfferBook closes all offers associated with the member 
            //get all borrow offers for member
            List<Offer> borrowoffers = lc.ListMyBorrowOffers(member);
            //loop through each offer setting status to closed
            foreach (var offer in borrowoffers)
            {
                offer.Status = OfferStatus.Closed.ToString(); // create an enum call OfferStatus
                offerDAC.UpdateById(offer);
            }
            //get all lend offers for member
            List<Offer> lendoffers = lc.ListMyOffers(member);
            //loop through each offer setting status to closed
            foreach (var offer in lendoffers)
            {
                offer.Status = OfferStatus.Closed.ToString(); // create an enum call OfferStatus
                offerDAC.UpdateById(offer);
            }

            //3. The MemberBook marks the member record as closed
            member.Status = "C";

            //update member table
            mDAC.UpdateById(member);



            //4. The MessagingSystem informs the user of successful deregistration
            //InformDeRegisteredUser(member);

        }

/*
        public void InformUser(Member member)
        {
            Message msg = CreateDeRegistrationMessage(member);

            MessagerComponent mclient = new MessagerComponent();
           

            mclient.SendMessage(msg);
        }

        public void InformVisitor(string email)
        {
            Message msg = CreateContactMessage(email);

            MessagerComponent mclient = new MessagerComponent();
            
            mclient.SendMessage(msg);
        }

        public void InformRegisteredUser(Member member)
        {
            Message msg = CreateRegistrationMessage(member);

            MessagerComponent mclient = new MessagerComponent();
             

            mclient.SendMessage(msg);
        }
        public void InformDeRegisteredUser(Member member)
        {
            Message msg = CreateDeRegistrationMessage(member);

            MessagerComponent mclient = new MessagerComponent();
            

            mclient.SendMessage(msg);
        }
*/
        #region Private
        private SMSMessage CreateSMS(string fromTelno, string toTelno, string msg)
        {
            if (string.IsNullOrEmpty(fromTelno))
                throw new ArgumentNullException("fromTelno");
            if (string.IsNullOrEmpty(toTelno))
                throw new ArgumentNullException("toTelno");

            if (string.IsNullOrEmpty(msg))
                throw new ArgumentNullException("msg");

            SMSMessage sms = new SMSMessage();
            sms.addressFrom = fromTelno;
            sms.addressTo = toTelno;
            sms.messageDate = DateTime.Today;
            sms.Body = msg;

            return sms;
        }

        private EmailMessage CreateEmail(string addressFrom, string addressTo, string msg)
        {
            if (string.IsNullOrEmpty(addressFrom))
                throw new ArgumentNullException("addressFrom");
            if (string.IsNullOrEmpty(addressTo))
                throw new ArgumentNullException("addressTo");

            if (string.IsNullOrEmpty(msg))
                throw new ArgumentNullException("msg");

            EmailMessage email = new EmailMessage();
            email.addressFrom = addressFrom;
            email.addressTo = addressTo;
            email.messageDate = DateTime.Today;
            email.subject = "Fanikiwa Registration";
            email.Body = msg;

            return email;
        }

        private EmailMessage CreateContactEmail(string addressFrom, string addressTo, string msg)
        {
            if (string.IsNullOrEmpty(addressFrom))
                throw new ArgumentNullException("addressFrom");
            if (string.IsNullOrEmpty(addressTo))
                throw new ArgumentNullException("addressTo");

            if (string.IsNullOrEmpty(msg))
                throw new ArgumentNullException("msg");

            EmailMessage email = new EmailMessage();
            email.addressFrom = addressFrom;
            email.addressTo = addressTo;
            email.messageDate = DateTime.Today;
            email.subject = "Fanikiwa Contact";
            email.Body = msg;

            return email;
        }

        private Message CreateRegistrationMessage(Member member)
        {
            Message ret = null;
            string msg = "Dear " + member.Surname + " " + member.OtherNames + "\n\nYou are now registered with Fanikiwa." + "\nYou can now start to Invest your money as an Investor or Get a Loan as a Borrower." + "\n\nRegards, \nFanikiwa";

            string fanikiwaTelno = Config.GetString("FANIKIWATELNO");
            string fanikiwaEmail = Config.GetString("FANIKIWAEMAIL");

            if ("SMS".Equals(member.InformBy.ToUpper()))
            {

                ret = this.CreateSMS(fanikiwaTelno, member.Telephone, msg);

            }
            else if ("EMAIL".Equals(member.InformBy.ToUpper()))
            {

                ret = this.CreateEmail(fanikiwaEmail, member.Email, msg);
            }
            return ret;

        }

        private Message CreateDeRegistrationMessage(Member member)
        {
            Message ret = null;
            string msg = "Dear " + member.Surname + " " + member.OtherNames + "\n\nYou are now deregistered from Fanikiwa. \nAll Accounts have Been closed and all Open Offers have been closed." + "\n\nRegards, \nFanikiwa";

            string fanikiwaTelno = Config.GetString("FANIKIWATELNO");
            string fanikiwaEmail = Config.GetString("FANIKIWAEMAIL");

            if ("SMS".Equals(member.InformBy.ToUpper()))
            {

                ret = this.CreateSMS(fanikiwaTelno, member.Telephone, msg);

            }
            else if ("EMAIL".Equals(member.InformBy.ToUpper()))
            {

                ret = this.CreateEmail(fanikiwaEmail, member.Email, msg);
            }
            return ret;

        }

        private Message CreateContactMessage(string email)
        {
            Message ret = null;
            string msg = "Fanikiwa Contact";
            string fanikiwaEmail = Config.GetString("FANIKIWAEMAIL");
            ret = this.CreateContactEmail(fanikiwaEmail, email, msg);
            return ret;
        }
        public ContactUs CreateContactUs(ContactUs _ContactUs)
        {
            ContactUsDAC _ContactUsDAC = new ContactUsDAC();

            ContactUs _returnedContactUs = _ContactUsDAC.Create(_ContactUs);

            return _returnedContactUs;
        }
        public void EditContactUs(ContactUs _ContactUs)
        {
            ContactUsDAC _ContactUsDAC = new ContactUsDAC();

            _ContactUsDAC.UpdateById(_ContactUs);
        }
        public List<ContactUs> GetAllContactUsList()
        {
            ContactUsDAC _ContactUsDAC = new ContactUsDAC();

            return _ContactUsDAC.Select();
        }
        public ContactUs GetContactUsById(ContactUs _ContactUs)
        {
            ContactUsDAC _ContactUsDAC = new ContactUsDAC();

            return _ContactUsDAC.SelectById(_ContactUs.Id);
        }
        public void DeleteContactUs(ContactUs _ContactUs)
        {
            ContactUsDAC _ContactUsDAC = new ContactUsDAC();

            _ContactUsDAC.DeleteById(_ContactUs.Id);
        }
        #endregion

    }
}
